apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodeserver
spec:
  replicas: 3
  serviceName: node-hs #hardless
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
      - name: nodeserver
        image: nailsonisrael/nodewebserver:v3.1
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: "vars-configmap"
          - secretRef:
              name: "secret-auth"
        volumeMounts:
          # mesma pasta raiz que ta sendo montada pelo docker
          - mountPath: "/var/www/pvc"
            name: app-vol

        # env:
        # - name: TITLE_ENV
        #   valueFrom:
        #     configMapKeyRef:
        #       name: vars-configmap
        #       key: TITLE_ENV
        # - name: PROJECT_NAME
        #   valueFrom:
        #     configMapKeyRef:
        #       name: vars-configmap
        #       key: PROJECT_NAME            
      volumes:
        - name: app-vol
          persistentVolumeClaim:
            claimName: mypvc # corrigido de "clainName" para "claimName"
  volumeClaimTemplates:
    - metadata:
        name: node-vol
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50M